### ISSUE TITLE
Versioning incompatibility with PyInstaller

### ISSUE THREAD

**Issue by nwhitehead** [jaraco/path.py#101]
When using PyInstaller with a trivial program that uses path.py, the build finishes but then the final executable does not work.

Steps to reproduce:

    pip install path.py pyinstaller
    echo "import path" > dummy.py
    pyinstaller dummy.py
    ./dist/dummy/dummy

Results in `pkg_resources.DistributionNotFound: The 'path.py' distribution was not found and is required by the application`.

My workaround is to comment out line 122:

    __version__ = pkg_resources.require('path.py')[0].version

I have no idea where exactly things are going wrong, it could be a bug in PyInstaller.

**Comment by daviddyball** [comment]
Not 100% sure if my problem is the same, but IPython no longer loads with path.py 7.6:

```
# ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/dist-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
  File "/usr/local/lib/python2.7/dist-packages/path.py", line 122, in <module>
    __version__ = pkg_resources.require('path.py')[0].version
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: path.py
```

Downgrading to `path.py==7.5` solved the issue for me.

**Comment by jaraco** [comment]
There are two separate issues here. In the first, it seems that PyInstaller isn't including the package metadata in the bundle. That is, although the distribution `path.py` was installed by pip, its `dist-info` is either not present or not discoverable in the PyInstaller environment. The latest `path.py` relies on that info for the version. I believe this can be fixed by not failing when the package metadata is unavailable.

The second report is probably related, but probably due to how path.py was installed in that environment. My guess is that `path.py` was copied directly into PYTHONPATH, and not installed by an installer such as setuptools or pip. This aspect also can be addressed by not failing when the package metadata is unavailable, though it can also be fixed by using an installer to install the package (either through `setup.py install` or `setup.py develop` on a checkout or using `easy_install` or `pip install` of the package). If I'm wrong about my assumptions here, please clarify.
