### ISSUE TITLE
Add "new_filename()" and "new_file()" method to tempdir

### ISSUE THREAD

**Issue by sametmax** [jaraco/path.py#110]
I recently had to do something like this:

```
from path import path:

with tempdir() as d:
    tempfile = d / str(uuid.uuid4())
    foo(tempfile)
    content = tempfile.bytes()
```

I wish I could have done:

```
with tempdir() as d:
    tempfile = d.new_filename()
    foo(tempfile)
    content = tempfile.bytes()
```

Which would abstract the creation of a unique filename in this tempdir, and would save me an import.

Something similar returning a file like object would also be nice:

```
with tempdir() as d:
    temp_path, file_like_object = d.new_file()
```

Or a file like_object with an attribute being a path object.

**Comment by jaraco** [comment]
I've been mostly pleased with my experiences working with py.path.local when it comes to the creation of temporary files with content in them. Perhaps we should consider some of the methods they supply, which may solve some of the aforementioned use cases.

Thinking about your first case, the `new_filename` just seems like a hard-coding of a particular method of generating a filename, and the code is only slightly simpler while also masking the mechanism used to generate the filename. One would have to look at the code or the docs to know that the filename is getting named with a UUID instead of say "FILE0001.txt". I suspect this is why there's no `new_filename` function in shutil. To the extent that it's general enough, it's too complicated, and to the extent that it's simple, it's not useful enough in the general case.

Thinking of your second suggestion, I do tend to avoid the creation of multiple return values. Plus, you can accomplish the same very easily with:

```
with tempdir() as d:
  temp_path = d.new_file()
  file_like_object = temp_path.open()
```

It's not quite as brief, but it's also clearer to someone using it what's happening. It's also easier to use the file-like object as a context:

```
  with temp_path.open() as file_like_object:
    ...
```

I might be convinced that a `new_filename` could be implemented, but what it would take to convince me is something that has a good docstring, that explains why and how someone would use such a method. 

I invite @sametmax or others to draft a proposal, either here or in a PR.

**Comment by jaraco** [comment]
Feel free to revive the conversation or provide a PR.
