### ISSUE TITLE
copytree "The destination directory must not already exist."

### ISSUE THREAD

**Issue by Gurdil** [jaraco/path.py#117]
I have been a problem using copytree feature, I need to save regularly a result directory and "The destination directory must not already exist." avoid doing it easily.

Bypassing example: 
```python
from path import path
from distutils.dir_util import copy_tree

dirResult = path('C:\result\')
dirSave = path('T:\save\')

while True:
    wait(60*10)
    copy_tree(dirResult, dirSave)
```

Does it seem acceptable to use the distutils copy_tree function by default in path.py?

**Comment by jaraco** [comment]
As as you've implied, path.Path objects already have a `copytree` method, which is simply the `shutil.copytree` function. This function is the Python stdlib best implementation of a copytree. Now you do point out that distutils provides a different `copy_tree` with different semantics, and that in particular, it allows copying a tree over an existing one. But since it is a utility function of distutils, I consider it less than fully supported.

And so while it might seem useful to expose `copy_tree` as a Path method, I just can't see a clean way to do that. I don't want to simply expose `distutils.dirutil.copy_tree` as `Path.copy_tree` and leave it to the users to figure out which method they want to call.

I also don't want to re-implement a copy-tree method in Path that somehow supports varying semantics.

What I would like to see is for the stdlib shutil to expose a function that suits your use case, and then Path could easily mirror that, and possibly even provide forward compatibility for that functionality.

What I would consider is a separate implementation of a `merge_tree` method that implements the behavior you're seeking, but avoids the distutils implementation details (like the `dry_run` parameter). Would you be interested in putting a pull request for something like this?

**Comment by jaraco** [comment]
Closing as languishing. Feel free to revive the conversation as time permits.
