### ISSUE TITLE
Update documentation links on PyPI

### ISSUE THREAD

**Issue by edbrannin** [jaraco/path.py#119]
The [path.py page on PyPI](https://pypi.python.org/pypi/path.py#downloads) still links to the [now-absent documentation on Pythonhosted.org](http://pythonhosted.org/path.py/)

It would be nice if:
1. The PyPI page pointed to https://pathpy.readthedocs.io/en/latest instead
2. The Pythonhosted page had a link directing us to the new documentation location.

**Comment by jaraco** [comment]
Yeah, this is the hassle I'm forced to do for every project. It's not possible to delete the link. My only option is to hand-assemble some documentation as a zip file and upload it to PyPI. That's what I did to add the now-absent documentation.

So (1) isn't possible, and (2) involves me crafting the docs in a zip file. If you want to do (2), I'll upload it. Otherwise, there's nothing to be done here except encourage others to stop using PyPI and use [https://pypi.org/](warehouse) instead.

**Comment by gazpachoking** [comment]
On my projects there is a button on pypi that says "If you would like to DESTROY any existing documentation hosted at http://pythonhosted.org/<projectname> Use this button, There is no undo." Would that not delete the link?

The README has the RTD link now, so next release that will get updated in the pypi text.

**Comment by jaraco** [comment]
That's a new feature. Pretty sure it wasn't there last I checked. Thanks! Documentation destroyed.

**Comment by jaraco** [comment]
And 9.0.1 pending release.
