### ISSUE TITLE
.rmdir_p not catch error FileNotFoundError

### ISSUE THREAD

**Issue by daassh** [jaraco/path.py#124]
The description of method '.rmdir_p' in doc: 
_Like rmdir(), but does not raise an exception if the directory is not empty or **does not exist**._
But I try code as follow:
```
Path('path_to_not_exists').rmdir_p()
```
and got error
```
FileNotFoundError: [WinError 2]
```
I check the code and find https://github.com/jaraco/path.py/blob/master/path.py#L1234， maybe it should be:
```
if e.errno != errno.ENOTEMPTY and e.errno != errno.EEXIST and e.errno != errno.ENOENT:
```
my ENV:
os: windows 7 64bit
python: 3.5.2 64bit

thanks

**Comment by jaraco** [comment]
I agree that sounds like a bug. I was going to throw together a test and fix for the issue, but instead spent my morning fixing #125 and #126 so that we have some [continuous integration tests running on Windows](https://ci.appveyor.com/project/jaraco/path-py).

Would you be willing to put together a pull request with:

- [ ] A test demonstrating the expected behavior (failing).
- [ ] The proposed fix as a subsequent commit, fixing the failing test.
- [ ] An update to the changelog describing what's changed (in an 0.0.1 bump).
