### ISSUE TITLE
Wondering the wisdom of using _next_class().

### ISSUE THREAD

**Issue by drakeguan** [jaraco/path.py#80]
I'm quite curious to know the wisdom and ideas of using **_next_class**, a ClassProperty, to create instances in lots of member functions.

**Comment by jaraco** [comment]
In general, subclasses want to generate new instances of the same class, but sometimes, it's necessary to generate more general classes.

Consider `tempdir(Path)`. It overrides _next_class such that when you invoke `tempdir() / 'foo'`, that resolves to a `Path` object instead of another `tempdir`. 

See bf82b390a3df6d for the original motivation.

**Comment by drakeguan** [comment]
Thanks for sharing this idea.

The motivation of this question is that `pylint` cannot figure out the type of the returned instances because this design. I guess `pylint` does not know what `cls` is during static code analysis.
