### ISSUE TITLE
Add "config_dir" class method.

### ISSUE THREAD

**Issue by jaraco** [jaraco/path.py#88]
I'd like to add a classmethod, "config_dir":

```
@classmethod
def config_dir(cls, app_name):
    """
    Return a path object referencing a suitable config
    directory for the relevant platform. Honors the
    `XDG Base Directory Specification
    <http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html>`_
    on Unix and App Data conventions on Windows.
    Ensures that directory exists.
    """
```

Thoughts?

**Comment by msabramo** [comment]
Seems reasonable to me.

**Comment by jaraco** [comment]
As I start to dive in with an implementation, I see issues. For one, a 'config' dir isn't the only directory one might require. The XDG specification also gives a spec for `data`, `cache`, and `runtime` dirs. It feels improper to only implement one of those.

**Comment by jaraco** [comment]
I've put together an implementation for consideration and feedback. There is one aspect of this implementation that I'd like to remove, and that's the implicitness of two things - that an `app_name` is always appended and that the target is always created. I think I want to change the implementation to only ever resolve the directories, and leave it to another function to handle what to do with the result.

**Comment by sametmax** [comment]
In that case, you may want to implement all dirs. App dirs does this : https://pypi.python.org/pypi/appdirs/1.4.0. 

Because path.py wants to be minimalist, we could choose the optional dependancy approach : 

- make it appear in "extra_requires=" (http://stackoverflow.com/questions/10572603/specifying-optional-dependencies-in-pypi-python-setup-py)  in setup.py so one can installed it with pip install path.py[sysdirs]
- make a conditional import in path.py (try / except ImportErrror);
- if the module is installed, expose a SysDir class with methods returning the dirs as Path objects.

**Comment by jaraco** [comment]
Shame on me for not searching for an existing implementation. I certainly don't want to create a duplicate, divergent, and less-complete implementation. I like your suggestion.

**Comment by sametmax** [comment]
Damn it, you beat me to it !  I got a very different approach though : https://github.com/sametmax/path.py/tree/sysdirs. I feel like my version has some advantages :

First, you can store the SysDirs object an reuse it without passing the params everytime. It will likely be done in a configuration stage, and avoid moving around a dictionary called app_dir_config just for that. 

Secondly, it mimic the appdirs API dynamically, so not only the appdirs documentation will still be valid, but if appdirs add a new property, it will be picked up automatically.

Also it offers a clear NotImplementedError if you try to use it without appdirs being installed with an helpful error message. 

Maybe I'm wrong but I feel like the current implementation doesn't allow to pass version, roaming, etc. Although know I think about it, mine has a bug with "multipath" (can be fixed though).

I like the fact that your version is a static method of Path, because it uses the current Path class.

Should we merge ?

Mine passes all the tox tests, but I need to add some tests for multipath apparently.

**Comment by jaraco** [comment]
> Maybe... the current implementation doesn't allow to pass [other parameters].

It does actually expose the full signature of the underlying appdirs functions.

I think a merge might be good. I haven't yet have a chance to review yours, but I will. The one aspect I liked most about my implementation was that the API provided a clear designation for the `scope` and `class` of the appdirs and in separate namespaces (not combining them into a single namespace as appdirs does). The other thing that is important to me in the implementation is that it should be easily to invoke in a single statement.

Does your implementation give usage examples? If not, would you add them so I can review the differences?

**Comment by jaraco** [comment]
I've taken some time to review your implementation.

I wasn't aware of the AppDirs class in my initial review of it. Indeed, they don't reference AppDirs in the docs, and AppDirs docstring indicates that it's a "convenience wrapper".

I'm not compelled by the re-use case, though I do usually prefer class wrappers for encapsulation.

I'm pretty sure my implementation has issues with multipath as well. The implementation wraps the result in a single path class even though appdirs returns a pathsep-concatenated string. For compatibility, I recommend we wrap that result in another `MultiPath` class, which is again a str/unicode, but which when iterated over will yield Path instances.

One thing that strikes me about your implementation is the rename of AppDirs to SysDirs. Is there a reason not to defer to ActiveState/appdirs for the naming convention?

**Comment by sametmax** [comment]
> I've taken some time to review your implementation.

> I wasn't aware of the AppDirs class in my initial review of it. Indeed, they don't reference AppDirs ithe docs, and AppDirs docstring indicates that it's a "convenience wrapper".

> I'm not compelled by the re-use case, though I do usually prefer class wrappers for encapsulation.

> I'm pretty sure my implementation has issues with multipath as well. The implementation wraps thresult in a single path class even though appdirs returns a pathsep-concatenated string. For compatibility, I recommend we wrap that result in another MultiPath class, which is again a str/unicode, but which when iterated over will yield Path instances.

:+1:

> One thing that strikes me about your implementation is the rename of AppDirs to SysDirs. Is there reason not to defer to ActiveState/appdirs for the naming convention?

I choose SysDirs because I think it's easier to understand what it will do than AppDirs. AppDirs feels like it's organising the structure of your app dir tree, while SysDirs give you directory names matching the system conventions. When you write a script or a daemon, you may want to write a log, although you are not making an "app". 

This has the additional benefit of allowing us add other directories later even if they are not related to app. E.G: download dir, music dir, video dir, document dir, desktop dir...

Thinking about it, we may want to rename it SysPath actually. Indeed, in the future, we may want to add path to important files such as the hosts file. So let's not close that door.

**Comment by jaraco** [comment]
@sametmax I'm struggling to imagine an implementation that meets your goals (re-usable class) without losing the ability to invoke the functions with their parameters. For example, I want to support this syntax:

(for now I'm using the 'app dirs' name; I'll deal with naming later)

```
Path.app_dirs.site.config('My App', version="1.0")
```

And you would also like to support something like:

```
app_dirs = AppDirPaths(Path, 'My App', version="1.0")
app_dirs.site.config()
```

Where `AppDirPaths` serves a similar purpose to the convenience wrapper `appdirs.AppDirs`.

I tried using `appdirs.AppDirs` to capture the wrapper when constructing AppDirPaths, but its properties do not allow the parameters to customized when they're called.

On further consideration, maybe this indicates a different usage, where `Path.app_dirs` is a callable, not a property, and the properties on the result are not. Yes, I think perhaps that's better. So this would be the canonical usage:

```
Path.app_dirs('My App', version="1.0").site.config
```

I'll work on that.

**Comment by jaraco** [comment]
Okay. I'm pretty happy with the latest implementation as found in [the branch](https://github.com/jaraco/path.py/tree/issue-88).

I believe all that's left to reconcile is the naming. I'm slightly inclined to stick with `app_dirs` because that's congruent with the upstream implementation (though doesn't concatenate words, following [PEP-8 guidelines](https://www.python.org/dev/peps/pep-0008/#function-names)).

Even as SysDirs or SysPaths may be more precise names, that precision doesn't in my mind provide enough value to justify the disparity with the upstream naming.

I don't feel strongly about it, though, so I'll defer to @sametmax and others if there's a consensus. @msabramo What's your take? Looking at [the changelog](https://github.com/jaraco/path.py/blob/issue-88/CHANGES.rst) for some indication as to the usage, what attribute name would you prefer?

**Comment by sametmax** [comment]
I see little value of following upstream convention as so few people knows about this lib and we are abstracting away anyway. However, if one day we want to add path to the trash directory or to the program files directory, where are we going to put it ? In app dir ? That would be weird. Yes, the current path are related to the app because it contains the app name, but the specificity of the path are definitely constraint by the OS, so SysPath makes more sense to me.

But, as you said, I can live with app_dir too. So I'll vote in favor in SysPath (explicitly stating it can be any path, not just a dir, and specific to the OS), but I app_dir is fine if needed.

**Comment by jaraco** [comment]
It doesn't strike me as weird that `AppDirs().trash` or `AppDirs().program_files` would reflect those special paths. In looking around, it seems that Windows and Mac refer to these directories as "special folders", so maybe "special" is the right namespace for them.

What about `Path.special().user.config()`, ... where `Path.special()` returns a `SpecialResolver` instance?

Then, there could be something like `Path.special().user.documents` or `Path.special().public.documents`.

I realize one reason I'm shying away from SysPath is because it sounds an awful lot like `sys.path`, and when spoken is indistinguishable. 

At this point, I'm convinced that keeping AppDirs isn't all that valuable, so I'm happy to drop it. And if the class is called a Resolver (rather than a Path, which it is not), then a `SystemResolver` class and `.system` method would provide a nice API.

@sametmax If you think about those options (`SystemResolver` and `.system()` vs. `SpecialResolver` and `.special()`), which do you prefer?

**Comment by sametmax** [comment]
You are righ about the sys.path confusion. +1 for special;

**Comment by jaraco** [comment]
Excellent. Thanks. Released as 7.7.

**Comment by Nodd** [comment]
I may be too late in the discussion, but why isn't `special` a property ? These empty parens seem to add nothing of value here.

**Comment by sametmax** [comment]
Well, I would use them to pass default values to "appname" and "username", is that the goal?

**Comment by jaraco** [comment]
That's right - the user needs a way to pass configuration parameters that may affect the selection of the target path. For some special folders, that's unnecessary, in which case the parameters may be omitted.

**Comment by Nodd** [comment]
OK, nevermind then.
