### ISSUE TITLE
sandboxing support for Path

### ISSUE THREAD

**Issue by grimnight** [jaraco/path.py#90]
Would it be possible to get a Path subclass with support for [sandboxing] paths?

[sandboxing]: http://docs.pyfilesystem.org/en/latest/concepts.html#sandboxing

**Comment by msabramo** [comment]
And you don't want to use PyFilesystem? You just want the one feature?

Curious what the use case is and if you might send a PR for this feature...?

**Comment by grimnight** [comment]
PyFilesystem is a great library, but a bit heavy dependency, path.py is a lot smaller.
My use case currently involves some personal projects, scripts that take relative
paths as arguments and takes actions on them, such as deleting them, which can
be dangerous if there is one too many `..` or `*`.
I do not know path.py well enough to make a pull request.

Besides PyFilesystem I have not seen another path manipulation library that has sandboxing.
If you know of one, please let me know.

**Comment by jaraco** [comment]
For the most part, path.py is a lightweight wrapper around stdlib functionality. Ironically, part of the reason it is smaller than PyFilesystem is because it has limited its scope. I just installed PyFilesystem and it's only one package. It has no dependencies or C extensions, so it's only larger than path.py in size and scope, but the installation case is roughly equivalent (vendoring, on the other hand might be more complicated). Over the years, path.py has grown larger to the point that it no longer fits comfortably in a single module, and especially if we start adding functionality like that proposed herein, it will put even more pressure for the tool to split into different modules such as PyFilesystem is organized.

I'm inclined to say that path.py shouldn't attempt to re-implement functionality already in another similar library unless there's a compelling reason to do so. Size of the package isn't a compelling reason. But let's explore anyway.

Since you're not prepared to make a pull request, could you at least write up a description of how path.py would implement this functionality? Describe what the user experience would be. Draft the documentation that explains this proposed feature and answers questions the user might have like, "how does it work," "when does it take effect," "how secure is it (or not)," "who should use it," and other questions, with examples.

If we have a spec to work from and content to serve as documentation, and someone can volunteer an implementation that doesn't degrade the current experience, I can see it being accepted.
