### ISSUE TITLE
question: why isn't `self` used as `src` for shutil-functions?

### ISSUE THREAD

**Issue by funkyfuture** [jaraco/path.py#98]
ciao,

i'm thinking about using the path.py-module in a project.

but i found it counter-intuitive and less effective in terms of simplifying my code when i stumpled over the fact that an instance isn't used as `src`-argument for the functions from `shutil` like `copy` etc. i wonder if this is intentional.

if it is not, i would work on patches to achieve that behaviour.

would you be interested in methods that allow merging filetrees from / to another?

**Comment by funkyfuture** [comment]
second thought: i would propose `_from`- `_to`-equivalents of the functions in question.

**Comment by jaraco** [comment]
The instance is used.

```
import path
# copy setup.py to setup2.py
p = path.Path('setup.py')
p.copyfile('setup2.py')
```

The reason that's not clear from the implementation is because the functions from shutil are copied into the Path namespace, so get bound to a Path instance (as the `src` parameter) when the method is retrieved.

I do awknowledge that the documentation is unclear on this usage, and because the functions are simply bound, their docstrings no longer accurately represent their usage in a Path instance.

The way to fix that would be to provide an explicit wrapper around each function, which becomes a lot of boilerplate code to copy signature just to replace the docstring. For example,

```
class Path:
    copy = shutil.copy
```

becomes

```
class Path:
    def copy(self, dst, *args, **kwargs):
        """
        Copy data and mode bits ("cp src dst"). See :func:`shutil.copy` for details.
        """
        return shutil.copy(self, dst, *args, **kwargs)
```

Then, you'd have to repeat something like that for every shutil function.

And in some ways that's worse because it masks the signature for the function. It's not possible to write a suitable docstring or signature because the implementation of `shutil.copy` changes between Python versions. For example, in Python 2, copyfile returns None, but on Python 3, it returns the name of the destination, and new optional parameters are added in future versions.

Given these tradeoffs, I don't see an obvious solution that's not heavy-handed. The lightweight mechanism is simple and elegant, but doesn't provide nice docs. Maybe another approach could be to provide documentation in the Path class itself describing what I've described above.

Thoughts?

**Comment by funkyfuture** [comment]
i see, thanks for your elaboration.

yes, i think a more in-depth documentation would be useful. i wasn't aware that it's so straightforward to bind a function into a class and that signature would stay the same. so, for me it would suffice to add some notes on that in the code where the functions get bound into the class, and an info above the API-reference that the generated documentation isn't perfectly valid at this and that point.

so, as i'm going to refactor now, would you be interested in a method with a signature like `shutil.copytree` that behaves like a `mergetree`? it's a wrapper around `copytree` and a helper function from distutils that's pretty useful.

**Comment by jaraco** [comment]
I'm not familiar with `mergetree` by name. Do please feel free to share what you're proposing, if you think it has broad value. Otherwise, consider simply subclassing Path in your application to extend its functionality.

**Comment by funkyfuture** [comment]
```mergetree(src, dst, symlinks=False, ignore=None, copy_function=copy2, ignore_dangling_symlinks=False)```

in difference to copytree, `dst` is allowed to exist. if it exists, the (not ignored) objects are copied into `dst`, overwriting objects with the same path. this is a functionality that's often asked for, actually simple to achieve - so simple it isn't worth an own module, and imo perfectly fitting into `path.py`.

propably i will open a pr concerning this later.

**Comment by jaraco** [comment]
> propably i will open a pr concerning this later.

Sounds great.

**Comment by funkyfuture** [comment]
thanks for the update, i ask myself if that is actually a bug in Sphinx.

**Comment by funkyfuture** [comment]
hm, it seems to bind the functions into the class has another downside. unless i'm overlooking something here, overriding attributes is not possible:

```python
from path import Path, tempdir

class path(Path):
    def copy2(self, dst, *args, **kwargs):
        if not dst.dirname().exists():
            dst.makedirs()
        super(Path, self).copy2(dst, *args, **kwargs)
```

fails into this:
```
    super(Path, self).copy2(dst, *args, **kwargs)
AttributeError: 'super' object has no attribute 'copy2'
```

**Comment by jaraco** [comment]
With super, you need to use `path` and not `Path`.
